version: 2.1
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout 
      - run: 
          name: "echo an env var that is part of our project"
          command: | 
            echo "text to output here" > output.txt
      - persist_to_workspace:
        root: /tmp/workspace
        paths:
          - target/output.txt    

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:      
      - attach_workspace:
        at: /tmp/workspace
      - run : "print putput"  
        command: | 
          cat output.txt
        
workflows:  
  workflow_jobs: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - save_hello_world_output 
      - print_output_file        
      